# # #
# dockerized nekoserv's services
#

version: '3.7'


networks:
  dummy:
  private:
  proxy:


services:

  main-services:
    image: hello-world
    container_name: main-services
    depends_on:
      - homepage
      - aria2-webui
      - flood
      - lidarr
      - medusa
      - metube
      - monit
      - pyload
      - radarr
      - sabnzbd
      - traefik
      - trilium
      - vpn-services


  vpn-services:
    image: hello-world
    container_name: vpn-services
    depends_on:
      - aria2
      - flaresolverr
      - jackett
      - nzbhydra2
      - openvpn-client
      - ping-me
      - rtorrent
      - rtorrent-rpc2


  homepage:
    build:
      context: dockerfiles/homepage
    container_name: homepage
    networks:
      - private
    expose:
      - "18083"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/homepage/config.yml:/home/homepage/assets/config.yml:ro
      - ~/docker-data/homepage/external-resources:/home/homepage/assets/external-resources:ro
      - ~/docker-data/homepage/icons:/home/homepage/assets/icons:ro
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.middlewares=global-auth@file"
      - "traefik.http.routers.homepage.tls.certresolver=default-ssl"


  aria2:
    build:
      context: dockerfiles/aria2
    container_name: aria2
    restart: unless-stopped
    depends_on:
      - openvpn-client
    network_mode: service:openvpn-client
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/aria2/aria2.conf:/etc/aria2.conf:ro
      - ~/docker-data/aria2/session:/home/aria2/session
      - ~/docker-data/aria2/cache-aria2:/home/aria2/.cache/aria2
      - ~/docker-data/aria2/dl:/home/aria2/dl
      - /mnt/nas/share/aria2:/home/aria2/complete
      - ~/docker-data/aria2/scripts:/home/aria2/scripts
    read_only: true
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1


  aria2-webui:
    build:
      context: dockerfiles/aria2-webui
    container_name: aria2-webui
    networks:
      - private
    expose:
      - "18082"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - ENV_ARIA2_CONTAINER_NAME=openvpn-client
      - ENV_ARIA2_PORT=6801
      - ENV_ARIA2_TOKEN=$ARG_ARIA2_TOKEN
    tmpfs:
      - /tmp
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/aria2`)"
      - "traefik.http.routers.aria2.tls=true"
      - "traefik.http.middlewares.aria2-stripprefix.stripprefix.prefixes=/aria2"
      - "traefik.http.routers.aria2.middlewares=aria2-auth-and-prefix"
      - "traefik.http.middlewares.aria2-auth-and-prefix.chain.middlewares=global-auth@file,aria2-stripprefix@docker"
      - "traefik.http.routers.aria2.tls.certresolver=default-ssl"


  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    depends_on:
      - openvpn-client
    network_mode: service:openvpn-client
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    read_only: false
    healthcheck:
      test: ["CMD", "curl", "--fail", "-so/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1


  flood:
    build:
      context: dockerfiles/flood
    container_name: flood
    networks:
      - private
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - FLOOD_OPTION_baseuri=/flood/
      - FLOOD_OPTION_host=0.0.0.0
      - FLOOD_OPTION_rundir=/home/flood/data/
      - FLOOD_OPTION_secret=$ENV_FLOOD_SECRET
      - FLOOD_OPTION_noauth=true
      - FLOOD_OPTION_rthost=$ENV_FLOOD_RT_HOST
      - FLOOD_OPTION_rtport=$ENV_FLOOD_RT_PORT
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/flood:/home/flood/data
      - ~/docker-data/dl/incomplete/torrent:/home/incomplete:ro
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flood.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/flood`)"
      - "traefik.http.routers.flood.tls=true"
      - "traefik.http.routers.flood.middlewares=global-auth@file"
      - "traefik.http.routers.flood.tls.certresolver=default-ssl"


  jackett:
    build:
      context: dockerfiles/jackett
    container_name: jackett
    depends_on:
      - openvpn-client
    network_mode: service:openvpn-client
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/jackett:/home/jackett/data
    read_only: true
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1


  lidarr:
    build:
      context: dockerfiles/lidarr
    container_name: lidarr
    networks:
      - private
    expose:
      - "8686"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/lidarr:/home/lidarr/data
      - ~/docker-data/dl/postprocessing/music:/home/postprocessing/music
      - /mnt/nas/musics:/home/lidarr/dl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/lidarr`)"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.middlewares=global-auth@file"
      - "traefik.http.routers.lidarr.tls.certresolver=default-ssl"


  medusa:
    build:
      context: dockerfiles/medusa
    container_name: medusa
    networks:
      - private
    expose:
      - "8081"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/medusa:/home/medusa/data
      - ~/docker-data/dl/postprocessing/tv:/home/postprocessing/tv
      - /mnt/nas/SERIES:/home/medusa/dl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medusa.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/medusa`)"
      - "traefik.http.routers.medusa.tls=true"
      - "traefik.http.routers.medusa.middlewares=global-auth@file"
      - "traefik.http.routers.medusa.tls.certresolver=default-ssl"


  metube:
    build:
      context: dockerfiles/metube
    container_name: metube
    networks:
      - dummy
    expose:
      - "8081"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - URL_PREFIX=/metube/
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/dl/incomplete/metube:/downloads
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/metube`)"
      - "traefik.http.routers.metube.tls=true"
      - "traefik.http.routers.metube.middlewares=global-auth@file"
      - "traefik.http.routers.metube.tls.certresolver=default-ssl"


  monit:
    build:
      context: dockerfiles/monit
    container_name: monit
    hostname: monit-docker
    depends_on:
      - socket-proxy
      - traefik
    networks:
      - dummy
      - private
      - proxy
    expose:
      - "2812"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_CONTAINER_LIST=$ENV_MONIT_DOCKER_LIST
      - ENV_SMTP_HOST=$ARG_MONIT_SMTP_HOST
      - ENV_SMTP_PORT=$ARG_MONIT_SMTP_PORT
      - ENV_SMTP_USR=$ARG_MONIT_SMTP_USR
      - ENV_SMTP_PASS=$ARG_MONIT_SMTP_PASS
      - ENV_ALERT_EMAIL=$ARG_MONIT_ALERT_EMAIL
    tmpfs:
      - /tmp:uid=1000,gid=1000
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monit.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/monit`)"
      - "traefik.http.routers.monit.tls=true"
      - "traefik.http.middlewares.monit-stripprefix.stripprefix.prefixes=/monit"
      - "traefik.http.middlewares.monit-redirect1.redirectregex.regex=^(.*)/monit-container/monit-container/(.*)"
      - "traefik.http.middlewares.monit-redirect1.redirectregex.replacement=$${1}/monit-container/$${2}"
      - "traefik.http.middlewares.monit-redirect2.redirectregex.regex=^https://$ENV_DOMAIN/monit-container/(.*)"
      - "traefik.http.middlewares.monit-redirect2.redirectregex.replacement=https://$ENV_DOMAIN/monit/monit-container/$${1}"
      - "traefik.http.middlewares.monit-redirect3.redirectregex.regex=^https://$ENV_DOMAIN/monit/monit-container/$$"
      - "traefik.http.middlewares.monit-redirect3.redirectregex.replacement=https://$ENV_DOMAIN/monit/"
      - "traefik.http.routers.monit.middlewares=monit-middlewares"
      - "traefik.http.middlewares.monit-middlewares.chain.middlewares=global-auth@file,monit-redirect1@docker,monit-redirect2@docker,monit-redirect3@docker,monit-stripprefix@docker"
      - "traefik.http.routers.monit.tls.certresolver=default-ssl"


  nzbhydra2:
    build:
      context: dockerfiles/nzbhydra2
      args:
        UID: 1000
        GID: 1000
    container_name: nzbhydra2
    depends_on:
      - openvpn-client
    network_mode: service:openvpn-client
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp:exec
    volumes:
      - ~/docker-data/nzbhydra2/data:/home/nzbhydra2/data
    read_only: true
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1


  openvpn-client:
    build: dockerfiles/openvpn-client
    container_name: openvpn-client
    cap_add:
      - net_admin
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      - private
    expose:
      - "5001"
    environment:
      - TZ=$ENV_TIMEZONE
      - CFG_OPEN_PORTS=$ENV_OVPN_OPEN_PORTS
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /dev/net:/dev/net:z
      - ~/docker-data/openvpn-config:/etc/openvpn/conf:ro
      - ~/docker-data/openvpn-config/resolv.conf:/etc/resolv.conf:ro
    read_only: true
    healthcheck:
      test: ["CMD", "drill", "-4", "TXT", "o-o.myaddr.l.google.com", "@8.8.8.8"]
      interval: 1m
      timeout: 2s
      retries: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/jackett`)"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.middlewares=global-auth@file"
      - "traefik.http.routers.jackett.tls.certresolver=default-ssl"
      - "traefik.http.routers.jackett.service=service-jackett"
      - "traefik.http.services.service-jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.nzbhydra2.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/nzbhydra`)"
      - "traefik.http.routers.nzbhydra2.tls=true"
      - "traefik.http.routers.nzbhydra2.middlewares=global-auth@file"
      - "traefik.http.routers.nzbhydra2.tls.certresolver=default-ssl"
      - "traefik.http.routers.nzbhydra2.service=service-nzbhydra2"
      - "traefik.http.services.service-nzbhydra2.loadbalancer.server.port=5076"


  ping-me:
    build:
      context: dockerfiles/ping-me
    container_name: ping-me
    networks:
      - private
    expose:
      - "39387"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    read_only: true
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1


  pyload:
    build:
      context: dockerfiles/pyload
      args:
        UID: 1000
        GID: 1000
    container_name: pyload
    networks:
      - dummy
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/pyload:/home/pyload
      - ~/docker-data/dl/incomplete/pyload:/home/pyload/Downloads/pyLoad
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pyload.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/pyload`)"
      - "traefik.http.routers.pyload.tls=true"
      - "traefik.http.routers.pyload.middlewares=global-auth@file"
      - "traefik.http.routers.pyload.tls.certresolver=default-ssl"


  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


  radarr:
    build:
      context: dockerfiles/radarr
      args:
        UID: 1000
        GID: 1000
    container_name: radarr
    networks:
      - private
    expose:
      - "7878"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/radarr:/home/radarr/data
      - ~/docker-data/dl/postprocessing/movies:/home/postprocessing/movies
      - ~/docker-data/dl/incomplete/torrent:/home/incomplete:ro
      - /mnt/nas/FILMS:/home/radarr/dl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.middlewares=global-auth@file"
      - "traefik.http.routers.radarr.tls.certresolver=default-ssl"


  rtorrent:
    build:
      context: dockerfiles/rtorrent
      args:
        UID: 1000
        GID: 1000
    container_name: rtorrent
    restart: unless-stopped
    depends_on:
      - openvpn-client
    network_mode: service:openvpn-client
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/rtorrent/config:/home/rtorrent
      - ~/docker-data/rtorrent/session:/home/rtorrent/session
      - ~/docker-data/nzbToMedia:/home/rtorrent/nzbToMedia
      - /mnt/nas/share:/home/rtorrent/share
      - ~/docker-data/dl/incomplete/torrent:/home/incomplete
      - ~/docker-data/dl/postprocessing:/home/postprocessing
      - ~/docker-data/flood/temp:/home/flood/data/temp:ro
    read_only: true
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "ping-me:39387"]
      interval: 10s
      timeout: 2s
      retries: 1
    stdin_open: true
    tty: true


  rtorrent-rpc2:
    build:
      context: dockerfiles/rtorrent-rpc2
    container_name: rtorrent-rpc2
    networks:
      - private
    expose:
      - "18081"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - ENV_CONTAINER_NAME=openvpn-client
      - ENV_RTORRENT_PORT=5001
    tmpfs:
      - /tmp
    read_only: true


  sabnzbd:
    build:
      context: dockerfiles/sabnzbd
      args:
        UID: 1000
        GID: 1000
    container_name: sabnzbd
    networks:
      - private
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/sabnzbd:/home/sabnzbd/config
      - ~/docker-data/nzbToMedia:/home/sabnzbd/nzbToMedia
      - /mnt/nas/share:/home/sabnzbd/complete
      - ~/docker-data/dl/incomplete/nzb:/home/incomplete
      - ~/docker-data/dl/postprocessing:/home/postprocessing
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/sabnzbd`)"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.middlewares=global-auth@file"
      - "traefik.http.routers.sabnzbd.tls.certresolver=default-ssl"


  traefik:
    image: traefik:2.10
    container_name: traefik
    depends_on:
      - socket-proxy
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      dummy:
        aliases:
          - dummy.traefik
      private:
        aliases:
          - private.traefik
      proxy:
        aliases:
          - proxy.traefik
    ports:
      - "443:443"
    environment:
      - TZ=$ENV_TIMEZONE
      - OVH_ENDPOINT=$ENV_OVH_ENDPOINT
      - OVH_APPLICATION_KEY=$ENV_OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET=$ENV_OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY=$ENV_OVH_CONSUMER_KEY
    tmpfs:
      - /tmp
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - ~/docker-data/traefik/conf:/etc/traefik:ro
      - ~/docker-data/traefik/ssl:/etc/traefik-ssl
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`$ENV_DOMAIN`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=global-auth@file"
      - "traefik.http.routers.dashboard.tls.certresolver=default-ssl"


  trilium:
    build:
      context: dockerfiles/trilium
      args:
        UID: 1000
        GID: 1000
    container_name: trilium
    networks:
      - dummy
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - TZ=$ENV_TIMEZONE
      - TRILIUM_DATA_DIR=/data
      - TRILIUM_PORT=8080
    tmpfs:
      - /tmp
    volumes:
      - ~/docker-data/trilium:/data
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`$ENV_DOMAIN`) && PathPrefix(`/trilium`)"
      - "traefik.http.routers.trilium.tls=true"
      - "traefik.http.middlewares.trilium-stripprefix.stripprefix.prefixes=/trilium"
      - "traefik.http.routers.trilium.middlewares=trilium-auth-and-prefix"
      - "traefik.http.middlewares.trilium-auth-and-prefix.chain.middlewares=global-auth@file,trilium-stripprefix@docker"
      - "traefik.http.routers.trilium.tls.certresolver=default-ssl"
      - "traefik.http.routers.trilium.service=service-trilium"
      - "traefik.http.services.service-trilium.loadbalancer.server.port=8080"
